import { DenounceItemProps, SideMenuItemData } from "@/types/types";
import { DENOUCE_TYPE, SideMenuItem } from "./enums";

const sideMenuData: { [key in SideMenuItem]: { icon: string; href: string } } =
  {
    [SideMenuItem.Dashboard]: {
      icon: "/images/dashboard.svg",
      href: "/dashboard",
    },
    [SideMenuItem.Configuracoes]: {
      icon: "/images/configuracoes.svg",
      href: "/dashboard/configuracoes",
    },
    [SideMenuItem.ConteudoHome]: {
      icon: "/images/home.svg",
      href: "/dashboard/conteudo-home",
    },
    [SideMenuItem.Cupons]: {
      icon: "/images/coupons.svg",
      href: "/dashboard/cupons",
    },
    [SideMenuItem.Selos]: {
      icon: "/images/selo.svg",
      href: "/dashboard/selos",
    },
    [SideMenuItem.Denuncias]: {
      icon: "/images/denuncia.svg",
      href: "/dashboard/denuncias",
    },
    [SideMenuItem.Usuarios]: {
      icon: "/images/usuarios.svg",
      href: "/dashboard/usuarios",
    },
    [SideMenuItem.PoliticasTermos]: {
      icon: "/images/politica.svg",
      href: "/dashboard/privacy",
    },
    [SideMenuItem.Series]: {
      icon: "/images/series.svg",
      href: "/dashboard/series",
    },
    [SideMenuItem.MeuPerfil]: {
      icon: "/images/meu-perfil.svg",
      href: "/dashboard/meu-perfil",
    },
  };

export const menuItem: SideMenuItemData[] = Object.entries(sideMenuData).map(
  ([name, { icon, href }]) => ({
    name: name as SideMenuItem,
    href,
    current: false,
    icon,
    alt: name as SideMenuItem,
  })
);

export const DenounceMock: DenounceItemProps[] = [
  {
    id: 1,
    denouncerId: 1,
    denouncerName: "John Doe",
    denounceType: DENOUCE_TYPE.CONTEUDO_IMPROPRIO,
    denounceDetails: "This user used hate speech in their comment",
    episodeImage: "https://i.imgur.com/Vw65lJs.jpeg",
    episodeId: 1,
    SerieName: "Example Series",
    autorName: "Jane Smith",
    autorId: 2,
    denouceData: "2021-10-01",
  },
  {
    id: 2,
    denouncerId: 2,
    denouncerName: "Jane Smith",
    denounceType: DENOUCE_TYPE.DIREITOS_AUTORAIS,
    denounceDetails: "This user is spamming the comments section",
    episodeImage: "https://i.imgur.com/Vw65lJs.jpeg",
    episodeId: 1,
    SerieName: "Example Series",
    autorName: "John Doe",
    autorId: 1,
    denouceData: "2021-10-02",
  },
  {
    id: 3,
    denouncerId: 3,
    denouncerName: "Marcelus Soares",
    denounceType: DENOUCE_TYPE.OUTROS,
    denounceDetails: "This user is spamming the comments section",
    episodeImage: "https://i.imgur.com/Vw65lJs.jpeg",
    episodeId: 1,
    SerieName: "Example Series",
    autorName: "Fernando Leoncio",
    autorId: 3,
    denouceData: "2021-10-02",
  },
  {
    id: 4,
    denouncerId: 4,
    denouncerName: "Fernando Leoncio",
    denounceType: DENOUCE_TYPE.SPAM,
    denounceDetails: "This user is spamming the comments section",
    episodeImage: "https://i.imgur.com/Vw65lJs.jpeg",
    episodeId: 1,
    SerieName: "Example Series",
    autorName: "Marcelus Soares",
    autorId: 4,
    denouceData: "2021-10-02",
  },
  {
    id: 5,
    denouncerId: 5,
    denouncerName: "John Doe",
    denounceType: DENOUCE_TYPE.CONTEUDO_IMPROPRIO,
    denounceDetails: "This user used hate speech in their comment",
    episodeImage: "https://i.imgur.com/Vw65lJs.jpeg",
    episodeId: 1,
    SerieName: "Example Series",
    autorName: "Jane Smith",
    autorId: 5,
    denouceData: "2021-10-01",
  },
  {
    id: 6,
    denouncerId: 6,
    denouncerName: "Jane Smith",
    denounceType: DENOUCE_TYPE.DIREITOS_AUTORAIS,
    denounceDetails: "This user is spamming the comments section",
    episodeImage: "https://i.imgur.com/Vw65lJs.jpeg",
    episodeId: 1,
    SerieName: "Example Series",
    autorName: "John Doe",
    autorId: 6,
    denouceData: "2021-10-02",
  },
  {
    id: 7,
    denouncerId: 7,
    denouncerName: "Marcelus Soares",
    denounceType: DENOUCE_TYPE.OUTROS,
    denounceDetails: "This user is spamming the comments section",
    episodeImage: "https://i.imgur.com/Vw65lJs.jpeg",
    episodeId: 1,
    SerieName: "Example Series",
    autorName: "Fernando Leoncio",
    autorId: 7,
    denouceData: "2021-10-02",
  },
  {
  id: 8,
  denouncerId: 8,
  denouncerName: "John Doe",
  denounceType: DENOUCE_TYPE.CONTEUDO_IMPROPRIO,
  denounceDetails: "This user used hate speech in their comment",
  episodeImage: "https://i.imgur.com/Vw65lJs.jpeg",
  episodeId: 1,
  SerieName: "Example Series",
  autorName: "Jane Smith",
  autorId: 8,
  denouceData: "2021-10-01",
},
{
  id: 9,
  denouncerId: 9,
  denouncerName: "Jane Smith",
  denounceType: DENOUCE_TYPE.DIREITOS_AUTORAIS,
  denounceDetails: "This user is spamming the comments section",
  episodeImage: "https://i.imgur.com/Vw65lJs.jpeg",
  episodeId: 1,
  SerieName: "Example Series",
  autorName: "John Doe",
  autorId: 9,
  denouceData: "2021-10-02",
},
{
  id: 10,
  denouncerId: 10,
  denouncerName: "Marcelus Soares",
  denounceType: DENOUCE_TYPE.OUTROS,
  denounceDetails: "This user is spamming the comments section",
  episodeImage: "https://i.imgur.com/Vw65lJs.jpeg",
  episodeId: 1,
  SerieName: "Example Series",
  autorName: "Fernando Leoncio",
  autorId: 10,
  denouceData: "2021-10-02",
},
{
  id: 11,
  denouncerId: 11,
  denouncerName: "Fernando Leoncio",
  denounceType: DENOUCE_TYPE.SPAM,
  denounceDetails: "This user is spamming the comments section",
  episodeImage: "https://i.imgur.com/Vw65lJs.jpeg",
  episodeId: 1,
  SerieName: "Example Series",
  autorName: "Marcelus Soares",
  autorId: 11,
  denouceData: "2021-10-02",
},
{
  id: 12,
  denouncerId: 12,
  denouncerName: "John Doe",
  denounceType: DENOUCE_TYPE.CONTEUDO_IMPROPRIO,
  denounceDetails: "This user used hate speech in their comment",
  episodeImage: "https://i.imgur.com/Vw65lJs.jpeg",
  episodeId: 1,
  SerieName: "Example Series",
  autorName: "Jane Smith",
  autorId: 12,
  denouceData: "2021-10-01",
},
{
  id: 13,
  denouncerId: 13,
  denouncerName: "Jane Smith",
  denounceType: DENOUCE_TYPE.DIREITOS_AUTORAIS,
  denounceDetails: "This user is spamming the comments section",
  episodeImage: "https://i.imgur.com/Vw65lJs.jpeg",
  episodeId: 1,
  SerieName: "Example Series",
  autorName: "John Doe",
  autorId: 13,
  denouceData: "2021-10-02",
},
{
  id: 14,
  denouncerId: 14,
  denouncerName: "Marcelus Soares",
  denounceType: DENOUCE_TYPE.OUTROS,
  denounceDetails: "This user is spamming the comments section",
  episodeImage: "https://i.imgur.com/Vw65lJs.jpeg",
  episodeId: 1,
  SerieName: "Example Series",
  autorName: "Fernando Leoncio",
  autorId: 14,
  denouceData: "2021-10-02",
},
{
  id: 15,
  denouncerId: 15,
  denouncerName: "Fernando Leoncio",
  denounceType: DENOUCE_TYPE.SPAM,
  denounceDetails: "This user is spamming the comments section",
  episodeImage: "https://i.imgur.com/Vw65lJs.jpeg",
  episodeId: 1,
  SerieName: "Example Series",
  autorName: "Marcelus Soares",
  autorId: 15,
  denouceData: "2021-10-02",
},
{
  id: 16,
  denouncerId: 16,
  denouncerName: "John Doe",
  denounceType: DENOUCE_TYPE.CONTEUDO_IMPROPRIO,
  denounceDetails: "This user used hate speech in their comment",
  episodeImage: "https://i.imgur.com/Vw65lJs.jpeg",
  episodeId: 1,
  SerieName: "Example Series",
  autorName: "Jane Smith",
  autorId: 16,
  denouceData: "2021-10-01",
},
{
  id: 17,
  denouncerId: 17,
  denouncerName: "Jane Smith",
  denounceType: DENOUCE_TYPE.DIREITOS_AUTORAIS,
  denounceDetails: "This user is spamming the comments section",
  episodeImage: "https://i.imgur.com/Vw65lJs.jpeg",
  episodeId: 1,
  SerieName: "Example Series",
  autorName: "John Doe",
  autorId: 17,
  denouceData: "2021-10-02",
}
];

export const commonInputClass = [
  "shadow appearance-none border border-neutral-950 rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline",
];